[phases.setup]
nixPkgs = ["nodejs"]
cmds = ["npm install -g serve@14.2.5"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["CI=false GENERATE_SOURCEMAP=false npm run build"]

[start]
cmd = "serve -s build -l $PORT"

[variables]
NODE_ENV = "production"
